test: &default

  # Credentials for REST APIs
  client_id: AXRS7wvILqvPgXh2bkhpl17oU3n3Bsc2ehcrkE2qipqLcxMwyCeRStlbL38Y8ojINxIuIptfv92x0n7z
  client_secret: EFqbV_UqSKs4luxZejUMiKQRD43PGiY_lOTcQt9JxKLsDZbap4kGm65vxOk2mC66QVY91KsUmESajN6T

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: vendedor@loadingco.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
